version: '3'

volumes:
  postgres_data: {}

services:
  db:
    image: postgres:11.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbpw
    ports:
      - "0.0.0.0:5432:5432"
  web:
    build: "."
    ports:
      - "0.0.0.0:5000:5000"
    links:
      - "db"